WIP skip sccache install if already in PATH

diff --git a/prepare_rust/action.yml b/prepare_rust/action.yml
--- a/prepare_rust/action.yml
+++ b/prepare_rust/action.yml
@@ -44,8 +44,17 @@ runs:
       shell: bash
 
     # cf prepare/action.yml for why not use hendrikmuhs/ccache-action
+    # MUST check if sscache already exists b/c prepare_rust CAN be called multiple time on the same host
+    # error: "mkdir: cannot create directory ‘/tmp/sscache’: File exists"
+    - name: Check if sccache already in PATH
+      if: fromJSON(inputs.install_sccache)
+      id: check-ssccache-exists
+      run: |
+        echo "::set-output name=ssccache-exists::$(command -v sccache &> /dev/null && echo 'true' || echo 'false')"
+      shell: bash
+
     - name: Install sccache custom prebuilt binary
-      if: ${{ fromJSON(inputs.install_sccache) }}
+      if: fromJSON(inputs.install_sccache) && !fromJSON(steps.check-ssccache-exists.outputs.ssccache-exists)
       run: |
         mkdir /tmp/sscache
         cd /tmp/sscache
@@ -56,12 +65,13 @@ runs:
       shell: bash
 
     - name: Setup env for sccache for Cargo/Rustc
-      if: ${{ fromJSON(inputs.install_sccache) }}
+      if: fromJSON(inputs.install_sccache)
       run: |
         echo "RUSTC_WRAPPER=/usr/local/bin/sccache" >> $GITHUB_ENV
       shell: bash
 
     - name: sccache
+      if: fromJSON(inputs.install_sccache)
       id: cache-sccache
       # using a fork that uploads even in case of failure
       # really useful for *_circuits b/c if a test fail after 20+mins of compilation it is wasteful to discard the compilation
