prepare(cpp): make ccache the default compiler
and remove custom logic for CMAKE_C_COMPILER_LAUNCHER/CMAKE_CXX_COMPILER_LAUNCHER:
already handled by CMake, no needed to duplicate the logic

fix: missing sudo in some places

diff --git a/prepare/action.yml b/prepare/action.yml
--- a/prepare/action.yml
+++ b/prepare/action.yml
@@ -133,16 +133,31 @@ runs:
     - name: Install ccache custom prebuilt binary
       if: fromJSON(inputs.install_ccache) && !fromJSON(steps.check-ccache-exists.outputs.ccache-exists)
       run: |
-        wget https://github.com/Interstellar-Network/gh-actions/releases/download/ccache-4.6/ccache -O /usr/local/bin/ccache
-        chmod +x /usr/local/bin/ccache
+        mkdir /tmp/ccache
+        cd /tmp/ccache
+        wget -O ccache.tar.xz https://github.com/ccache/ccache/releases/download/v4.6.1/ccache-4.6.1-linux-x86_64.tar.xz
+        tar -xf ccache.tar.xz --strip-components=1
+        chmod +x ccache
+        sudo mv ccache /usr/local/bin/ccache
         ccache --show-config
       shell: bash
 
-    - name: Setup env for ccache for our CMakePresets.json presets
+    # https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_LAUNCHER.html#variable:CMAKE_%3CLANG%3E_COMPILER_LAUNCHER
+    - name: Setup env for ccache for CMake
       if: fromJSON(inputs.install_ccache)
       run: |
-        echo "ENV_CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
-        echo "ENV_CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
+        echo "CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
+        echo "CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Make CCache the default compiler
+      if: fromJSON(inputs.install_ccache)
+      run: |
+        sudo ln -s ccache /usr/local/bin/gcc
+        sudo ln -s ccache /usr/local/bin/g++
+        cc --version
+        gcc --version
+        g++ --version
       shell: bash
 
     # write a kind of compiler_id for the cache key at the next step
@@ -267,7 +282,7 @@ runs:
     - name: Check mold(linker) exists
       id: check-mold-exists
       run: |
-        echo "::set-output name=mold-exists::$(command -v g++-10 &> /dev/null && echo 'true' || echo 'false')"
+        echo "::set-output name=mold-exists::$(command -v mold &> /dev/null && echo 'true' || echo 'false')"
       shell: bash
 
     # there is: # - uses: rui314/setup-mold@v1
@@ -275,7 +290,8 @@ runs:
     - name: Install mold(linker)
       if: (!fromJSON(steps.check-mold-exists.outputs.mold-exists))
       run: |
-        wget -O- https://github.com/rui314/mold/releases/download/v$MOLD_VERSION/mold-$MOLD_VERSION-$(uname -m)-linux.tar.gz | tar -C /usr/local --strip-components=1 -xzf -
+        wget -O- https://github.com/rui314/mold/releases/download/v$MOLD_VERSION/mold-$MOLD_VERSION-$(uname -m)-linux.tar.gz | sudo tar -C /usr/local --strip-components=1 -xzf -
+        sudo chmod +x /usr/local/bin/mold
       env:
         MOLD_VERSION: 1.3.1
       shell: bash
@@ -284,6 +300,13 @@ runs:
     - name: Make mold the default
       # make sure it works even if "mold" is already /usr/bin/ld else "ln: '/usr/local/bin/mold' and '/usr/local/bin/mold' are the same file"
       run: |
-        ln -sf /usr/local/bin/mold $(realpath /usr/bin/ld) || true
+        echo current linker: $(which ld) = $(realpath /usr/bin/ld)
+        echo ls -al ld = $(ls -al /usr/bin/ld)
+        ld --version
+        sudo ln -sfv /usr/local/bin/mold /usr/bin/ld && echo "mold set up!" || echo "failed to set up mold..."
+        echo new linker: $(which ld) = $(realpath /usr/bin/ld)
+        echo ls -al ld = $(ls -al /usr/bin/ld)
+        /usr/bin/ld --version || echo "/usr/bin/ld --version fail!"
+        file /usr/bin/ld || echo "file /usr/bin/ld fail!"
         ld --version
       shell: bash
